{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials-play-services-auth",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "13128144"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.5.0-sources.jar",
          "url": "credentials-play-services-auth-1.5.0-sources.jar",
          "size": 45065,
          "sha512": "12921f2166eb10c1f475fa62e8cc8f3a825ee0e2b946f4a7b9d607b32c6cb2f27783f42ef34b1833695edd148494e0570e09c48169fc8f88ddecc595f9d74974",
          "sha256": "fc5a79c79170a1b643e7694282fdfe9150bf4f8a3b6509ac2930b8a619892c79",
          "sha1": "abe5cfba0c60722158a7de12fea0227d55b49cd0",
          "md5": "0fd50114ed8737ddba888d3504c63597"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.5.0.aar",
          "url": "credentials-play-services-auth-1.5.0.aar",
          "size": 192376,
          "sha512": "d83836ded5a4e7bd5b1cb65370a5d39ce4481e0f3ec2a90c3a9dc1e39c9d880724188852ede46e957fae551d6d54006e55f7a495cf877c733b7320c566d7e91f",
          "sha256": "713644485b1cb44cc4e4f1aa76a9835cdfaaf855e11739b8b25c34d3f06b5ee4",
          "sha1": "642afdb24a0a40e3bcfa19d52979baef072c2da9",
          "md5": "271a1b21ab85341e7dbdf2b3b0bebc7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.1.1"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-blockstore",
          "version": {
            "requires": "16.4.0"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-fido",
          "version": {
            "requires": "21.0.0"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-identity-credentials",
          "version": {
            "requires": "16.0.0-alpha02"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.libraries.identity.googleid",
          "module": "googleid",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "androidx.credentials",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.5.0.aar",
          "url": "credentials-play-services-auth-1.5.0.aar",
          "size": 192376,
          "sha512": "d83836ded5a4e7bd5b1cb65370a5d39ce4481e0f3ec2a90c3a9dc1e39c9d880724188852ede46e957fae551d6d54006e55f7a495cf877c733b7320c566d7e91f",
          "sha256": "713644485b1cb44cc4e4f1aa76a9835cdfaaf855e11739b8b25c34d3f06b5ee4",
          "sha1": "642afdb24a0a40e3bcfa19d52979baef072c2da9",
          "md5": "271a1b21ab85341e7dbdf2b3b0bebc7d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.5.0-versionMetadata.json",
          "url": "credentials-play-services-auth-1.5.0-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}