{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "13128144"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-sources.jar",
          "url": "credentials-1.5.0-sources.jar",
          "size": 250066,
          "sha512": "048da32faacfe7720251f1ca078de551c5bf2cff6c744b89472c29ac7108d1c959f2580beae863592255cdeacdc76c13cbeb7c0c08adf7d554ce6cef896eb564",
          "sha256": "b309e3b4391ca273cc518d7a5c9d43e0a4126a4bc254ff7f7c7ebc4f55972241",
          "sha1": "4d299a045632780167ca065f0181206a55855e63",
          "md5": "0c75a545bff02f6bace64e2abe795874"
        },
        {
          "name": "credentials-1.5.0-samples-sources.jar",
          "url": "credentials-1.5.0-samples-sources.jar",
          "size": 7243,
          "sha512": "4802d83b3197e0faf36b8968e23723ad598d1954bdc5353bbe7193cd28f00fb0d41e98b28df9cae41584153608b7e52215c29dc8089d8785b2a4b83f34e4a003",
          "sha256": "fe1e7e44cf21e3cfd6858d14fba9da11aff6a3dc9d25b2bb634afb5a7dae73ae",
          "sha1": "1c39e28debbbbfaf621ec1643048b3ae9e7c745e",
          "md5": "44b66a46acc1d1332daf97f2211fe1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0.aar",
          "url": "credentials-1.5.0.aar",
          "size": 617567,
          "sha512": "281bbabb95c756ff2e8c9f9b2129969f3184911a0edb34ac6b6944e6cd711ae353e1553e4d0e8030bdb5b2429ad45d9f259cdcdd751269dffac260ade80ef9f5",
          "sha256": "00162f3d0244a42a8b9527f3cc6fb3bf36d655960c65b979bef250e5116f1453",
          "sha1": "7927656f62f11a2ed98ba61c0982005aaee0533f",
          "md5": "93fe1c8972736c830f36db9e8507b773"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0.aar",
          "url": "credentials-1.5.0.aar",
          "size": 617567,
          "sha512": "281bbabb95c756ff2e8c9f9b2129969f3184911a0edb34ac6b6944e6cd711ae353e1553e4d0e8030bdb5b2429ad45d9f259cdcdd751269dffac260ade80ef9f5",
          "sha256": "00162f3d0244a42a8b9527f3cc6fb3bf36d655960c65b979bef250e5116f1453",
          "sha1": "7927656f62f11a2ed98ba61c0982005aaee0533f",
          "md5": "93fe1c8972736c830f36db9e8507b773"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-versionMetadata.json",
          "url": "credentials-1.5.0-versionMetadata.json",
          "size": 69612,
          "sha512": "f76661ee6c401cbf119fde318354a9760f3225fd557bbb4bda4e0da840e4ae09acab26ffa730e27020a3d648eb25a9903e4c6249d35300aa3328c2466382b4d3",
          "sha256": "5b022a222395a7d64bc95888004c918944fd303bf06e1f4349c8df2419a1edc6",
          "sha1": "d059967b83dc866a7f5a91b11a9a18c78cec33f6",
          "md5": "a998b7411d4c750de1f00210978dd1b7"
        }
      ]
    }
  ]
}